Neos:
  Neos:
    fusion:
      autoInclude:
        FormatD.HubSpot: true
  Form:
    presets:
      default:
        finisherPresets:
          'FormatD.Hubspot:HubspotFormFinisher':
            implementationClassName: FormatD\HubSpot\Form\Finishers\HubSpotFormFinisher
      fusion:
        finisherPresets:
          'FormatD.HubSpot:HubSpotFormFinisher':
            implementationClassName: FormatD\HubSpot\Form\Finishers\HubSpotFormFinisher
  Fusion:
    defaultContext:
      HFile: 'FormatD\HubSpot\Eel\HubspotFileHelper'
