FormatD:
  HubSpot:
    mappingEelContext:
      String: Neos\Eel\Helper\StringHelper
      Array: Neos\Eel\Helper\ArrayHelper
      Date: Neos\Eel\Helper\DateHelper
      Configuration: Neos\Eel\Helper\ConfigurationHelper
      Math: Neos\Eel\Helper\MathHelper
      Json: Neos\Eel\Helper\JsonHelper
      I18n: Neos\Flow\I18n\EelHelper\TranslationHelper
      q: Neos\Eel\FlowQuery\FlowQuery::q
    api:
      portalId: ''
      accessToken: ''
    formFinisherMappings:
      default:
        firstname:
          objectTypeId: '0-1'
          name: 'firstname'
          value: '${fieldValue}'
        lastname:
          objectTypeId: '0-1'
          name: 'lastname'
          value: '${fieldValue}'
        company:
          objectTypeId: '0-1'
          name: 'company'
          value: '${fieldValue}'
        email:
          objectTypeId: '0-1'
          name: 'email'
          value: '${fieldValue}'
        phone:
          objectTypeId: '0-1'
          name: 'phone'
          value: '${fieldValue}'
        subject:
          objectTypeId: '0-5'
          name: 'subject'
          value: "${'Anfrage von ' + formValues.company}"
        content:
          objectTypeId: '0-5'
          name: 'content'
          value: '${fieldValue}'